In this class we will use PyTorch instead of Keras+Tensorflow. PyTorch is a deep learning framework that puts Python first. 

PyTorch videos by 莫煩 Moven: https://www.youtube.com/watch?v=KBdb53NrVAc&list=PLXO45tsB95cJxT0mL0P3-G0rBcLSvVkKH&index=7 

PyTorch by Sung Kim from HKUST (English)
https://www.youtube.com/watch?v=SKq-pmkekTk&list=PLlMkM4tgfjnJ3I-dbhO9JTw7gNty6o_2m 

In [1]:
import torch

In [2]:
import numpy as np

# List

In [3]:
[1, 2, 3, 4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [4]:
[ [1, 2, 3], [4, 5, 6]]

[[1, 2, 3], [4, 5, 6]]

# List <-> Array

In [5]:
x = [ [1, 2, 3], [4, 5, 6]]

In [6]:
y = np.array(x)

In [7]:
y

array([[1, 2, 3],
       [4, 5, 6]])

# Reshape Array

In [8]:
y.reshape(1, 6)

array([[1, 2, 3, 4, 5, 6]])

In [9]:
y.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [10]:
y.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
y.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

# List <-> Tensor

In [12]:
x = [ [1, 2, 3], [4, 5, 6]]

In [13]:
z = torch.FloatTensor(x)

In [14]:
z


 1  2  3
 4  5  6
[torch.FloatTensor of size 2x3]

# Reshape Tensor

In [15]:
z.view(1, 6)


 1  2  3  4  5  6
[torch.FloatTensor of size 1x6]

In [16]:
z.view(3, 2)


 1  2
 3  4
 5  6
[torch.FloatTensor of size 3x2]

# Array <-> Tensor

In [17]:
x = [[1, 2, 3], [4, 5, 6]]

In [18]:
y = np.array(x)

In [19]:
z = torch.from_numpy(y)

In [20]:
z


 1  2  3
 4  5  6
[torch.IntTensor of size 2x3]

In [21]:
y = z.numpy()

In [22]:
y

array([[1, 2, 3],
       [4, 5, 6]])

# Array multiplication 

In [23]:
x1 = [ [1, 2, 3], [4, 5, 6]]

In [24]:
x2 = [0.3, 0.2, 0.1]

In [25]:
y1 = np.array(x1)

In [26]:
y1

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
y1.shape

(2, 3)

In [28]:
y2 = np.array(x2)

In [29]:
y2

array([0.3, 0.2, 0.1])

In [30]:
y2.shape

(3,)

In [31]:
y2 = y2.reshape(3, 1)

In [32]:
y2.shape

(3, 1)

In [33]:
y2

array([[0.3],
       [0.2],
       [0.1]])

In [34]:
w = np.matmul(y1, y2)

In [35]:
w

array([[1. ],
       [2.8]])

In [36]:
w.shape

(2, 1)

# Tensor multiplication 

In [37]:
x1 = [ [1, 2, 3], [4, 5, 6]]

In [38]:
x2 = [0.3, 0.2, 0.1]

In [39]:
z1 = torch.FloatTensor(x1)

In [40]:
z1


 1  2  3
 4  5  6
[torch.FloatTensor of size 2x3]

In [41]:
z1.shape

torch.Size([2, 3])

In [42]:
z2 = torch.FloatTensor(x2)

In [43]:
z2


 0.3000
 0.2000
 0.1000
[torch.FloatTensor of size 3]

In [44]:
z2.shape

torch.Size([3])

In [45]:
z2 = z2.view(3, 1)

In [46]:
z2.shape

torch.Size([3, 1])

In [47]:
z2


 0.3000
 0.2000
 0.1000
[torch.FloatTensor of size 3x1]

In [48]:
w = torch.mm(z1, z2)

In [49]:
w


 1.0000
 2.8000
[torch.FloatTensor of size 2x1]

In [50]:
w.shape

torch.Size([2, 1])

# Numpy's array operations do not support GPU acceleration

Numpy provides an n-dimensional array object, and many functions for manipulating these arrays. Numpy is a generic framework for scientific computing; it does not know anything about computation graphs, or deep learning, or gradients. 

Numpy is a great framework, but it cannot utilize GPUs to accelerate its numerical computations. For modern deep neural networks, GPUs often provide speedups of 50x or greater, so unfortunately numpy won't be enough for modern deep learning.

# Tensor support GUP accelerated array opeations

A PyTorch Tensor is conceptually identical to a numpy array: a Tensor is an n-dimensional array, and PyTorch provides many functions for operating on these Tensors. Like numpy arrays, PyTorch Tensors do not know anything about deep learning or computational graphs or gradients; they are a generic tool for scientific computing.

However unlike numpy, PyTorch Tensors can utilize GPUs to accelerate their numeric computations. To run a PyTorch Tensor on GPU, you simply need to cast it to a new datatype.

https://github.com/jcjohnson/pytorch-examples